name: AppConfiguration-GoFeatureManagement CI

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    branches:
      - main
      - 'release/**'

jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: ["1.22", "1.23", "1.24", "1.25"]

    steps:
    - name: Check out code
      uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@7b8cf10d4e4a01d4992d18a89f4d7dc5a3e6d6f4 # v4.3.0
      with:
        go-version: ${{ matrix.go-version }}
        cache: true

    - name: Install dependencies
      working-directory: ./featuremanagement
      run: go mod download

    - name: Build
      working-directory: ./featuremanagement
      run: go build -v ./...

    - name: Test
      working-directory: ./featuremanagement
      run: go test -race -v  ./...
      if: runner.os != 'Windows'

    - name: Test (without race detector)
      working-directory: ./featuremanagement
      run: go test -v ./...
      if: runner.os == 'Windows'